#!/usr/bin/env python3
"""rerank_lean.py — produce a high-confidence candidate queue from the Lean census.

Applies the corrected policy from the framework note:
  - defs/abbrevs are more freely hideable (often plumbing)
  - theorems/lemmas hide only with strong "intended-internal" signals:
      (no docstring) AND (name_pattern in {underscore_prefix, aux, internal_namespace})
  - encapsulation clusters (the PR-38702 shape) get their own tier:
      a hub def with high n_signature_refs from same module +
      low external_users (so it's plausibly refactorable)

Outputs three tiers:
  - tier_1_solo : single-decl autonomous-agent targets (mech_hidable + intent_safe)
  - tier_2_module_bundle : group tier-1 by defining_module for cleaner batch PRs
  - tier_3_encap_hub : human-review candidates — PR-38702-shape encapsulation refactors

Each row carries module-level signals (blast cone, leverage rank, edit count)
so the queue is sortable by impact.

Output: out/ranked_candidates_lean.jsonl + RANKED_SUMMARY.md
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict, Counter
from pathlib import Path

import networkx as nx

sys.path.insert(0, str(Path(__file__).resolve().parent))
import paths  # noqa: E402

LEAN = paths.CENSUS                  # accepts .gz via paths.open_jsonl
CHURN = paths.CHURN_BLAST
GRAPH = paths.DATA / "lakeprof.graph.json"
OUT_JSONL = paths.RANKED_UNCOMPRESSED
OUT_MD = paths.DATA / "RANKED_SUMMARY.md"

# All policy lives in policy.toml; this module is the loader.
# To add or remove a forbidden attribute / name pattern, edit policy.toml only.
import policy as _policy  # noqa: E402

NEVER_HIDE_KINDS = _policy.never_hide_kinds()
FORBIDDEN_NAME_PATTERNS = _policy.forbidden_name_patterns()
FORBIDDEN_MODULE_PREFIXES = _policy.forbidden_module_prefixes()
INTENT_SAFE_KINDS = set(_policy.tier_1().get("intent_safe_kinds", ["def", "abbrev"]))
INTENT_SAFE_THEOREM_PATTERNS = set(
    _policy.tier_1().get("intent_safe_theorem_patterns",
                         ["underscore_prefix", "aux", "internal_namespace"]))


def is_synthesized_aux(name: str) -> bool:
    """True if the decl name looks auto-generated by the elaborator.

    These cannot be made `private` independently — they inherit visibility
    from the parent type or function. So they're not actionable PR targets.
    """
    return _policy.is_synthesized_aux(name)


def is_intent_safe(r: dict) -> bool:
    """Apply the corrected policy: defs/abbrevs freely; theorems with strong intent."""
    if r["is_private"]:
        return False
    kind = r["kind"]
    if kind in NEVER_HIDE_KINDS:
        return False
    if is_synthesized_aux(r["fq_name"]):
        return False
    if r.get("forbidden_attrs"):
        return False
    if r.get("name_pattern", "") in FORBIDDEN_NAME_PATTERNS:
        # e.g. simps_projection — meta-time consumer makes term-graph blind
        return False
    if kind in INTENT_SAFE_KINDS:
        return True
    if kind in {"theorem", "lemma"}:
        # Must have NO docstring (= author didn't mark as API)
        # AND name pattern indicates internal intent
        return (not r.get("has_docstring", False)
                and r.get("name_pattern", "normal") in INTENT_SAFE_THEOREM_PATTERNS)
    return False


def is_forbidden_module(module: str) -> bool:
    """True if module path should be filtered out at tier-1 (pre-filter).

    Modules under Mathlib.Tactic.*, Mathlib.Meta.*, Mathlib.Lean.* are
    dominated by extension-registered helpers that revert during iterate.
    Filtering them upstream avoids ~25% noise without losing yield.
    """
    return any(module.startswith(prefix) for prefix in FORBIDDEN_MODULE_PREFIXES)


def is_mech_hidable(r: dict) -> bool:
    """A decl is mechanically hidable iff no public-surface name resolution
    would break from privatizing it.

    Resolution shapes that matter:
      - External users (`n_external_users == 0`): any cross-module reference
        breaks because the importing module never had visibility.
      - Same-module signature references (`n_signature_refs == 0`): a
        public theorem whose *type* mentions the decl exposes the
        now-private name to downstream importers via its statement.

    Same-module *body* references (intra-module-refs minus signature-refs)
    do not constrain privatization: Lean 4 keeps private decls visible
    inside their defining module, so proofs that reference the decl
    continue to type-check after the visibility flip.
    """
    return (not r["is_private"]
            and r.get("n_external_users", 0) == 0
            and r.get("n_signature_refs", 0) == 0)


def is_encap_hub_candidate(r: dict) -> bool:
    """A hub-shaped candidate for the sub-module encapsulation pattern.

    Membership rules:
      - Type-shaped: `def`, `abbrev`, or `ctor` (structure constructors are
        load-bearing hubs in the same way defs are; the iterate-revert loop
        catches any case where a constructor isn't actually privatizable).
      - At least 2 same-module decls reference it in their type signature
        (a "cluster" of just the hub itself isn't worth a sub-module split).
        Score-based sort separates small hubs from large ones.
      - External users bounded: at most 30 cross-module consumers (any more
        and the sub-module's public-import burden outweighs the cache-cut
        benefit).
      - No forbidden attributes.
    """
    if r["is_private"]:
        return False
    if r["kind"] not in ("def", "abbrev", "ctor"):
        return False
    if is_synthesized_aux(r["fq_name"]):
        return False
    if r.get("forbidden_attrs"):
        return False
    n_sig = r.get("n_signature_refs", 0)
    n_ext = r.get("n_external_users", 0)
    return n_sig >= 2 and n_ext <= 30


def main():
    print(f"loading {LEAN.name}...")
    rows = []
    for l in paths.open_jsonl(LEAN):
        try: rows.append(json.loads(l))
        except: pass
    print(f"  {len(rows):,} decls")

    cb = json.loads(CHURN.read_text())
    top_leverage = {r["module"]: r for r in cb["top_leverage"]}
    top30 = set(top_leverage)

    import gzip
    graph_gz = paths.DATA / "lakeprof.graph.json.gz"
    if GRAPH.exists():
        g_data = json.loads(GRAPH.read_text())
    elif graph_gz.exists():
        with gzip.open(graph_gz, "rb") as f:
            g_data = json.loads(f.read().decode("utf-8"))
    else:
        raise FileNotFoundError(f"neither {GRAPH} nor {graph_gz} exists")
    g = nx.DiGraph()
    for n in g_data["nodes"]:
        g.add_node(n["id"], time=n.get("time", 0.0))
    for e in g_data["edges"]:
        g.add_edge(e["source"], e["target"])

    blast_cp: dict[str, float] = {}
    blast_size: dict[str, int] = {}
    for m in g.nodes:
        anc = nx.ancestors(g, m)
        blast_size[m] = len(anc)
        blast_cp[m] = sum(g.nodes[a].get("time", 0.0) for a in anc)
    for m, lev in top_leverage.items():
        blast_cp[m] = max(blast_cp.get(m, 0.0), lev["blast_cp_s"])

    def module_score(m: str) -> float:
        """Combine blast cone + top-30 status + edit count into a per-module weight."""
        bcp = blast_cp.get(m, 0.0)
        is_t30 = m in top30
        edits = top_leverage.get(m, {}).get("edits", 0)
        return (1.0 - math.exp(-bcp / 100.0)) * (3.0 if is_t30 else 1.0) * (1.0 + math.log1p(edits) / 3.0)

    # ---- Tier 1: solo intent-safe decls ----
    tier1 = [r for r in rows if is_mech_hidable(r) and is_intent_safe(r)
             and not is_forbidden_module(r["defining_module"])]
    for r in tier1:
        r["_module_score"] = module_score(r["defining_module"])
        # Per-decl score: pure module score (single decl)
        r["_score"] = r["_module_score"]

    print(f"\ntier 1 (solo intent-safe + mech-hidable, filtered): {len(tier1):,}")
    print(f"  by kind: {dict(Counter(r['kind'] for r in tier1))}")
    print(f"  by name_pattern: {dict(Counter(r['name_pattern'] for r in tier1))}")
    print(f"  in top-30 modules: {sum(1 for r in tier1 if r['defining_module'] in top30):,}")

    # ---- Tier 2: bundle by module ----
    by_mod = defaultdict(list)
    for r in tier1:
        by_mod[r["defining_module"]].append(r)
    tier2_bundles = []
    for m, decls in by_mod.items():
        if len(decls) < 3:
            continue
        bundle = {
            "module": m,
            "n_decls": len(decls),
            "decls": [r["fq_name"] for r in decls[:80]],  # cap at 80 per PR
            "n_decls_capped": min(len(decls), 80),
            "kinds": dict(Counter(r["kind"] for r in decls)),
            "blast_cp_s": blast_cp.get(m, 0.0),
            "blast_size": blast_size.get(m, 0),
            "is_top30": m in top30,
            "module_edits": top_leverage.get(m, {}).get("edits"),
            "score": module_score(m) * len(decls),
        }
        tier2_bundles.append(bundle)
    tier2_bundles.sort(key=lambda b: -b["score"])

    print(f"\ntier 2 (module bundles, ≥3 solo decls/module): {len(tier2_bundles):,} bundles")
    total_bundled = sum(b["n_decls"] for b in tier2_bundles)
    print(f"  total decls bundled: {total_bundled:,}")

    # ---- Tier 3: encapsulation hubs ----
    # Module weight enters as log(1+bcp) rather than the tier-1/2 saturation
    # form. Saturation maxes out at ~1.0 by bcp≈500, so for the ~99% of
    # mathlib above that floor, "where am I" stops discriminating and only
    # cluster shape ranks hubs — burying small-but-high-leverage clusters
    # (e.g. PR-38702's Real.equivCauchy: n_sig=2 in a bcp≈8.7k module).
    # log1p compresses the 100× bcp spread to ~5×, comparable in magnitude
    # to n_sig (2-50) and 1/(1+n_ext) (0.03-1), so all three signals stay
    # visible. Raw bcp would dominate; log keeps the trade-off balanced.
    tier3_hubs = [r for r in rows if is_encap_hub_candidate(r)]
    for r in tier3_hubs:
        bcp = blast_cp.get(r["defining_module"], 0.0)
        r["_module_score"] = math.log1p(bcp)
        r["_score"] = (
            r["_module_score"]
            * r["n_signature_refs"]
            * (1.0 / (1.0 + r["n_external_users"]))  # fewer ext users = easier refactor
        )
    tier3_hubs.sort(key=lambda r: -r["_score"])
    print(f"\ntier 3 (encap hubs: def/abbrev/ctor with n_sig_refs≥2, ≤30 ext): {len(tier3_hubs):,}")

    # ---- Write output ----
    OUT_JSONL.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JSONL.open("w") as f:
        for r in sorted(tier1, key=lambda x: -x["_score"]):
            f.write(json.dumps({"tier": "1_solo", **{k: v for k, v in r.items() if not k.startswith("_")}, "score": r["_score"]}) + "\n")
        for b in tier2_bundles:
            f.write(json.dumps({"tier": "2_bundle", **b}) + "\n")
        for r in tier3_hubs:
            f.write(json.dumps({"tier": "3_encap", **{k: v for k, v in r.items() if not k.startswith("_")}, "score": r["_score"]}) + "\n")
    print(f"\nwrote {OUT_JSONL}")

    # ---- Markdown summary ----
    lines = []
    lines.append("# Ranked candidate queue (Lean census)")
    lines.append("")
    lines.append(f"_Generated from `census_lean.jsonl` ({len(rows):,} decls)._")
    lines.append("")
    lines.append("Three tiers, in priority order. Apply the corrected policy from the")
    lines.append("framework note: defs/abbrevs hide more freely; theorems only with strong")
    lines.append("intent signals (no docstring + internal name pattern); encapsulation")
    lines.append("clusters get their own tier for human review.")
    lines.append("")
    lines.append("## Headline numbers")
    lines.append("")
    lines.append(f"- **{len(tier1):,}** tier-1 solo candidates (mech-hidable AND intent-safe)")
    lines.append(f"- **{len(tier2_bundles):,}** tier-2 module bundles (group tier-1 by module, ≥3 decls)")
    lines.append(f"- **{len(tier3_hubs):,}** tier-3 encapsulation hubs (PR-38702-shape, human review)")
    lines.append("")
    lines.append("## Tier 1 — solo intent-safe candidates (top 25 by module score)")
    lines.append("")
    lines.append("| score | kind | pattern | docstr | module / decl |")
    lines.append("|---:|---|---|:---:|---|")
    for r in sorted(tier1, key=lambda x: -x["_score"])[:25]:
        docstr = "Y" if r.get("has_docstring") else "."
        lines.append(f"| {r['_score']:.1f} | {r['kind']} | {r['name_pattern']} | {docstr} | `{r['fq_name']}` |")
    lines.append("")
    lines.append("## Tier 2 — module bundles (top 25 by total impact)")
    lines.append("")
    lines.append("Each bundle is one mechanical PR. Cap at 80 decls per PR; modules with more get split.")
    lines.append("")
    lines.append("| score | n_decls | T30 | edits | module |")
    lines.append("|---:|---:|:---:|---:|---|")
    for b in tier2_bundles[:25]:
        t30 = "Y" if b["is_top30"] else "."
        ed = b["module_edits"] or "-"
        lines.append(f"| {b['score']:.1f} | {b['n_decls']} | {t30} | {ed} | `{b['module']}` |")
    lines.append("")
    lines.append("## Tier 3 — encapsulation hubs (top 25 by score)")
    lines.append("")
    lines.append("Each hub is a candidate for the PR-38702 refactor pattern: privatize the")
    lines.append("hub def + the lemmas whose signatures reference it; extract to a sub-module")
    lines.append("if needed; have the (≤30) external consumers `public import` the sub-module.")
    lines.append("")
    lines.append("| score | sig_refs | ext_users | docstr | module / hub |")
    lines.append("|---:|---:|---:|:---:|---|")
    for r in tier3_hubs[:25]:
        docstr = "Y" if r.get("has_docstring") else "."
        lines.append(f"| {r['_score']:.1f} | {r['n_signature_refs']} | {r['n_external_users']} | {docstr} | `{r['fq_name']}` |")
    lines.append("")
    OUT_MD.write_text("\n".join(lines))
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
